scoring:
  weights:
    advanced:
      wsjf: 0.5
      ice: 0.1
      technicalDebt: 0.3
      security: 0.1
  
  thresholds:
    minScore: 10
    maxRisk: 0.8
    securityBoost: 2.0
    complianceBoost: 1.8

discovery:
  sources:
    - gitHistory
    - staticAnalysis
    - issueTrackers
    - vulnerabilityDatabases
    - performanceMonitoring
    - userFeedback
  
  tools:
    staticAnalysis:
      - ruff
      - mypy
      - bandit
      - safety
    security:
      - bandit
      - safety
      - pip-audit
    performance:
      - pytest-benchmark
      - memory-profiler

execution:
  maxConcurrentTasks: 1
  testRequirements:
    minCoverage: 80
    performanceRegression: 5
  rollbackTriggers:
    - testFailure
    - buildFailure
    - securityViolation

maturity:
  level: advanced
  percentage: 85
  nextReview: 30