version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "terragon-labs"
    assignees:
      - "terragon-labs"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    # Enhanced security and performance settings
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        # Allow patch updates for security fixes
    groups:
      production-dependencies:
        patterns:
          - "pandas*"
          - "numpy*"
          - "scikit-learn*"
          - "pyyaml*"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "mypy*"
          - "bandit*"
        update-types:
          - "minor"
          - "patch"
    # Security-first updates
    enable-beta-ecosystems: true

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "terragon-labs"
    assignees:
      - "terragon-labs"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "terragon-labs"
    assignees:
      - "terragon-labs"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"