global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'observer-coordinator-insights'
    environment: 'production'

rule_files:
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Application metrics
  - job_name: 'observer-coordinator-insights'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Database metrics (if applicable)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Python application specific metrics
  - job_name: 'python-app-metrics'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics/python'
    scrape_interval: 10s

  # Clustering algorithm performance metrics
  - job_name: 'clustering-metrics'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics/clustering'
    scrape_interval: 30s

  # Data processing pipeline metrics
  - job_name: 'data-pipeline-metrics'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics/pipeline'
    scrape_interval: 20s

  # Security and compliance metrics
  - job_name: 'security-metrics'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics/security'
    scrape_interval: 60s

# Remote storage configuration (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "prometheus"
#       password: "password"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "prometheus"
#       password: "password"