apiVersion: v1
kind: Namespace
metadata:
  name: quantum-autonomous-sdlc
  labels:
    name: quantum-autonomous-sdlc
    version: "6.0"
    component: production
    managed-by: terragon-labs
    quantum-enabled: "true"
  annotations:
    description: "Quantum Autonomous SDLC Production Environment"
    contact: "quantum@terragon-labs.com"
    documentation: "https://github.com/terragon-labs/observer-coordinator-insights"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quantum-resource-quota
  namespace: quantum-autonomous-sdlc
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: quantum-limit-range
  namespace: quantum-autonomous-sdlc
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim