apiVersion: v1
kind: Namespace
metadata:
  name: observer-coordinator-insights
  labels:
    name: observer-coordinator-insights
    environment: production
    app.kubernetes.io/name: observer-coordinator-insights
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "v4.0.0"
    app.kubernetes.io/component: system
    app.kubernetes.io/part-of: terragon-analytics
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    terragon.io/description: "Enterprise neuromorphic clustering system"
    terragon.io/owner: "platform-team@terragon-labs.com"
    terragon.io/compliance: "gdpr,ccpa,pdpa"